Algoritmo "Lista 2 (atividade 19")
// 
//  
//
Var
 nota1,nota2,media:real
  nome:caractere


Inicio

escreva("Qual é o seu nome: ")
leia(nome)
escreva("Digite sua primeira nota: ")
leia(nota1)
escreva("Digite sua segunda nota: ")
leia(nota2)
media <- (nota1 + nota2)/2
se media>= 7 entao
escreva("Parabens ", nome, " sua media é: ", media, " você foi aprovado")
senao
escreva("Sua media é:", media," ",nome, " você nâo foi aprovado")
fimse






Fimalgoritmo
