Algoritmo "Lista 2 (atividade 24")
// 
//  
//
Var
distancia, km1, km2:real

Inicio
escreva("Qual a distância em km quer ir : ")
leia(distancia)
km1 <- distancia*0.50
km2 <- distancia*0.45

se distancia >= 200  entao
escreva( " o valor a ser pago pelos ",distancia,"km rodados será de: ", km2)
senao
escreva( " o valor a ser pago pelos ",distancia,"km rodados será de: ", km1)
fimse










Fimalgoritmo
